// 展厅目录：大脑地图上的脑区、按《Stahl 精神药理学精要》章节的分组、角色图鉴，以及还在筹备中的小剧场。
// 脑区：每一集的 scene.js 在 meta 里写了 regions，展厅会自动把它挂到对应的脑区下。
// 按章节：下面 chapters 里列出每个小节对应的剧集 id；新做好一集，把 id 写进对应小节即可。
// 新做好一集后，把它从下面的 planned 里删掉即可；想预告新主题，就加进对应的 planned。
window.AnimaCatalog = {
  regions: {
    pfc: { name: "前额叶皮层", fact: "大脑的“总指挥”：负责计划、专注、控制冲动。它发育得最晚，要到 25 岁左右才完全成熟。", planned: [] },
    striatum: { name: "纹状体", fact: "管动作和习惯。多巴胺在这里帮忙把动作“启动”起来，缺了多巴胺，动作就会变慢、变僵。", planned: [] },
    nac: { name: "伏隔核", fact: "奖赏中心：好吃的、好玩的、被夸奖，都会让这里的多巴胺升高，让人“还想再来一次”。", planned: [] },
    amygdala: { name: "杏仁核", fact: "大脑的“警报器”，负责害怕和紧张，只有一颗杏仁那么大，左右各一个。", planned: [] },
    hippo: { name: "海马", fact: "新记忆的“收件箱”，形状像一只小海马。长期压力和阿尔茨海默病都会让它变小。", planned: [] },
    hypo: { name: "下丘脑和垂体", fact: "管睡觉、吃饭、体温和激素。垂体分泌的泌乳素，平时被多巴胺“按住”。", planned: [] },
    midbrain: { name: "中脑", fact: "腹侧被盖区和黑质是多巴胺神经元的“老家”，好几条多巴胺通路都从这里出发。", planned: [] },
    brainstem: { name: "脑干", fact: "中缝核是 5-HT 的老家，蓝斑是去甲肾上腺素的老家，它们的纤维几乎通到大脑的每个角落。", planned: [] },
    synapse: { name: "突触（放大看）", fact: "神经元之间的“小邮局”。几乎所有精神科药物，都是在突触里起作用的。", planned: [] },
  },
  // 按原书章节（第 5 版）分组
  parts: [
    { id: "basics", name: "基础篇", book: "第 1～3 章", desc: "化学神经传递，以及药物的靶点：转运体、受体、酶和离子通道", planned: [] },
    { id: "psychosis", name: "精神病与抗精神病药", book: "第 4～5 章", desc: "多巴胺、5-HT、谷氨酸网络，以及抗精神病药怎样起作用", planned: [] },
    { id: "mood", name: "心境障碍与治疗", book: "第 6～7 章", desc: "抑郁的单胺和神经营养假说，抗抑郁药为什么要等几周", planned: [] },
    { id: "anxiety", name: "焦虑与创伤", book: "第 8 章", desc: "杏仁核的警报、GABA 刹车和抗焦虑药", planned: [] },
    { id: "pain", name: "慢性疼痛", book: "第 9 章", desc: "疼痛信号为什么会被“放大”", planned: [] },
    { id: "sleep", name: "睡眠与觉醒", book: "第 10 章", desc: "食欲素、组胺和睡眠开关", planned: [] },
    { id: "adhd", name: "注意缺陷多动障碍", book: "第 11 章", desc: "前额叶的信号与噪音，以及兴奋剂怎样帮忙", planned: [] },
    { id: "dementia", name: "痴呆", book: "第 12 章", desc: "阿尔茨海默病里的乙酰胆碱和谷氨酸", planned: [] },
    { id: "addiction", name: "冲动、强迫与成瘾", book: "第 13 章", desc: "奖赏回路怎样被“劫持”", planned: [] },
  ],
  // 按原书目录（第 5 版各章开头的目录，不含每章的“小结”）：每个小节，以及讲这个小节的剧集 id
  // eps 里的 id 还没做出来时，这个小节在展厅里显示“筹备中”；一集可以出现在多个小节下
  chapters: [
    { n: 1, name: "化学神经传递", sections: [
      { name: "神经传递的解剖基础和化学基础", eps: ["synapse"] },
      { name: "化学神经传递的原理：递质、经典/逆行/容积传递、兴奋-分泌偶联", eps: ["neurotransmission-types", "endocannabinoid"] },
      { name: "信号转导级联：第二信使、磷酸化蛋白和基因表达", eps: ["signal-cascades", "g-protein", "plasticity"] },
      { name: "表观遗传", eps: ["plasticity"] },
      { name: "关于 RNA：可变剪接和 RNA 干扰", eps: ["rna-splicing"] },
    ] },
    { n: 2, name: "转运体、受体和酶：精神药物的作用靶点", sections: [
      { name: "神经递质转运体作为药物靶点", eps: ["transporter-families"] },
      { name: "G 蛋白偶联受体和激动剂谱", eps: ["agonist", "receptor-regulation"] },
      { name: "酶作为精神药物的作用位点", eps: ["enzyme-inhibitors"] },
      { name: "细胞色素 P450 药物代谢酶", eps: ["cyp450", "pharmacokinetics"] },
    ] },
    { n: 3, name: "离子通道：精神药物的作用靶点", sections: [
      { name: "配体门控离子通道", eps: ["ion-channels"] },
      { name: "电压敏感离子通道：钠通道和钙通道", eps: ["voltage-channels"] },
      { name: "离子通道和神经传递", eps: ["neurotransmission-types", "ion-channels"] },
    ] },
    { n: 4, name: "精神病、精神分裂症和递质网络：多巴胺、5-HT、谷氨酸", sections: [
      { name: "精神病的症状", eps: ["psychosis"] },
      { name: "精神病的三大假说和它们的递质网络", eps: ["dopamine-lifecycle", "glutamate-system", "serotonin-lifecycle"] },
      { name: "经典多巴胺假说", eps: ["psychosis", "dopamine-receptors"] },
      { name: "谷氨酸假说", eps: ["glutamate-pathways"] },
      { name: "5-HT 假说", eps: ["serotonin-psychosis", "serotonin-receptors"] },
      { name: "精神分裂症：典型的精神病性障碍", eps: ["neurodevelopment"] },
      { name: "其他精神病性障碍：痴呆相关、心境相关、帕金森病精神病", eps: ["other-psychoses", "serotonin-psychosis"] },
    ] },
    { n: 5, name: "靶向多巴胺和 5-HT 受体：所谓的“抗精神病药”", sections: [
      { name: "阻断中脑边缘/中脑纹状体 D2 受体：抗精神病作用", eps: ["antipsychotics"] },
      { name: "阻断 D2 受体引起继发性阴性症状", eps: ["secondary-negative"] },
      { name: "阻断结节漏斗 D2 受体：泌乳素升高", eps: ["antipsychotics"] },
      { name: "阻断黑质纹状体 D2 受体：运动副作用", eps: ["basal-ganglia-loops", "motor-side-effects", "tardive"] },
      { name: "第一代（传统）抗精神病药", eps: ["antipsychotic-fingerprints"] },
      { name: "靶向 5-HT2A 受体（同时或不同时阻断 D2）", eps: ["antipsychotics", "serotonin-psychosis"] },
      { name: "5-HT1A 和 D2 部分激动剂", eps: ["agonist", "antipsychotic-fingerprints"] },
      { name: "受体结合特性和其他疗效、副作用", eps: ["antipsychotic-fingerprints", "antipsychotic-metabolic"] },
      { name: "几种第一代 D2 拮抗剂的药理特点", eps: ["antipsychotic-fingerprints"] },
      { name: "“平”“酮”“哌”：各药物的药理特点", eps: ["antipsychotic-fingerprints", "clozapine", "long-acting-injectables"] },
      { name: "精神分裂症的未来治疗", eps: ["muscarinic-antipsychotic"] },
    ] },
    { n: 6, name: "心境障碍和递质网络：去甲肾上腺素与 GABA", sections: [
      { name: "心境障碍的描述：心境谱、单相和双相、混合特征", eps: ["depression", "bipolar"] },
      { name: "心境障碍的神经生物学：递质、单胺受体假说、神经可塑性", eps: ["norepinephrine-system", "gaba-system", "monoamine-brakes", "hpa-axis", "inflammation-depression"] },
      { name: "心境障碍的症状和回路", eps: ["symptom-circuits"] },
    ] },
    { n: 7, name: "心境障碍的治疗：“抗抑郁药”和“心境稳定剂”", sections: [
      { name: "抑郁治疗疗效的定义：反应、缓解和复发", eps: ["treatment-outcomes"] },
      { name: "经典单胺再摄取抑制剂在单相抑郁中效果如何", eps: ["antidepressants"] },
      { name: "重新定义“心境稳定剂”", eps: ["mood-stabilizers"] },
      { name: "单相抑郁的药物", eps: ["antidepressants", "monoamine-brakes", "multimodal-antidepressants", "tca", "enzyme-inhibitors", "neurosteroids"] },
      { name: "单相抑郁的难治", eps: ["augmentation-trd", "ketamine"] },
      { name: "双相谱系的药物", eps: ["mood-stabilizers"] },
      { name: "心境障碍的未来治疗", eps: ["future-antidepressants"] },
    ] },
    { n: 8, name: "焦虑、创伤及其治疗", sections: [
      { name: "焦虑障碍的症状维度", eps: ["anxiety"] },
      { name: "杏仁核和恐惧的神经生物学", eps: ["anxiety", "fear-outputs"] },
      { name: "皮层-纹状体-丘脑-皮层环路和担忧", eps: ["worry-loop"] },
      { name: "苯二氮䓬类抗焦虑药", eps: ["anxiety", "ion-channels"] },
      { name: "α2δ 配体作为抗焦虑药", eps: ["worry-loop", "ion-channels"] },
      { name: "5-HT 和焦虑", eps: ["fear-outputs", "worry-loop"] },
      { name: "焦虑中的去甲肾上腺素亢进", eps: ["norepinephrine-system", "fear-outputs"] },
      { name: "恐惧条件化和恐惧消退", eps: ["ptsd"] },
      { name: "各类焦虑障碍的治疗：惊恐、社交焦虑、创伤后应激、广泛性焦虑", eps: ["anxiety-subtypes"] },
    ] },
    { n: 9, name: "慢性疼痛及其治疗", sections: [
      { name: "什么是疼痛", eps: ["pain"] },
      { name: "神经病理性疼痛：外周和中枢机制", eps: ["neuropathic-pain"] },
      { name: "脊髓后角的下行突触和慢性疼痛的治疗", eps: ["pain"] },
      { name: "靶向慢性疼痛中被敏化的回路", eps: ["pain", "neuropathic-pain"] },
      { name: "纤维肌痛的伴随症状", eps: ["fibromyalgia"] },
    ] },
    { n: 10, name: "睡眠和觉醒障碍及其治疗：组胺和食欲素网络", sections: [
      { name: "睡眠和觉醒的神经生物学", eps: ["sleep", "histamine", "rem-sleep", "circadian"] },
      { name: "失眠", eps: ["sleep"] },
      { name: "失眠的治疗：催眠药", eps: ["hypnotics"] },
      { name: "白天过度嗜睡", eps: ["daytime-sleepiness", "narcolepsy", "restless-legs"] },
      { name: "促醒药和白天过度嗜睡的治疗", eps: ["wake-promoting"] },
    ] },
    { n: 11, name: "注意缺陷多动障碍及其治疗", sections: [
      { name: "症状和回路：前额叶的障碍", eps: ["adhd"] },
      { name: "多巴胺和去甲肾上腺素“调谐”前额叶不够好", eps: ["adhd", "alpha2a-hcn"] },
      { name: "神经发育和 ADHD", eps: ["adhd-development"] },
      { name: "ADHD 的治疗", eps: ["stimulants", "alpha2a-hcn"] },
    ] },
    { n: 12, name: "痴呆：病因、对症治疗和乙酰胆碱网络", sections: [
      { name: "痴呆的诊断和病因", eps: ["dementia", "dementia-types"] },
      { name: "针对 Aβ 的疾病修饰治疗", eps: ["amyloid-cascade"] },
      { name: "在太晚之前诊断阿尔茨海默病", eps: ["dementia-biomarkers"] },
      { name: "痴呆的对症治疗概述", eps: ["dementia"] },
      { name: "靶向乙酰胆碱：改善记忆和认知", eps: ["acetylcholine-system", "dementia"] },
      { name: "靶向谷氨酸：改善记忆和认知", eps: ["dementia"] },
      { name: "痴呆的行为症状", eps: ["dementia-agitation"] },
      { name: "痴呆中精神病和激越的药物治疗", eps: ["dementia-agitation", "serotonin-psychosis"] },
    ] },
    { n: 13, name: "冲动、强迫和成瘾", sections: [
      { name: "什么是冲动和强迫", eps: ["ocd-impulsivity"] },
      { name: "神经环路和冲动-强迫障碍", eps: ["ocd-impulsivity", "addiction"] },
      { name: "物质成瘾", eps: ["addiction", "opioid-receptors", "alcohol-opioids", "nicotine", "endocannabinoid", "hallucinogens"] },
      { name: "行为成瘾：赌博、暴食等", eps: ["behavioral-addictions"] },
      { name: "强迫及相关障碍", eps: ["ocd-impulsivity"] },
      { name: "冲动控制障碍", eps: ["behavioral-addictions"] },
    ] },
  ],
  // 即将开播：还没开始做的新栏目，先放预告。key 是主持人（Anima.CAST 里的角色）
  upcoming: [
    { key: "drug", name: "副作用诊察室", tag: "为什么会这样", hook: "药明明是来治病的，怎么会口干、犯困、长胖、一站起来就头晕？",
      desc: "药物访客常常顺手敲错了门。每集挑一种常见副作用，看看是哪扇门被多敲了一下。", eps: ["一扇 H1 门，又困又饿", "M1 门被堵：口干、便秘、看不清", "α1 门被堵：起身时眼前一黑"] },
    { key: "MAO", name: "药物撞车现场", tag: "相互作用", hook: "两种药单独用都好好的，碰到一起却出了事？",
      desc: "清扫员带你回到“事故现场”，一步步还原两种药在身体里是怎么互相影响的。", eps: ["两路加码：5-HT 综合征", "肝脏工人被拦住，另一种药迟迟下不了班", "吸烟让某些药代谢变快"] },
    { key: "GABA", name: "吃药冷知识", tag: "答疑", hook: "抗抑郁药为什么要等几周才见效？停药为什么要慢慢减？",
      desc: "图书管理员翻开笔记，用受体和突触的变化，回答大家最常问的“为什么”。", eps: ["为什么药效要等两三周", "停药太快，受体来不及适应", "安眠药为什么会越吃越不管用"] },
    { key: "5HT", name: "受体卡牌图鉴", tag: "收集", hook: "5-HT2A、D2、H1、M1……这些字母数字到底是谁？",
      desc: "一种受体一张卡：住在哪里、被打开会怎样、被堵上又会怎样。看完一集，就把卡收进图鉴。", eps: ["5-HT 受体家族全员集合", "多巴胺受体 D1 到 D5", "同一扇门，不同的钥匙"] },
    { key: "DA", name: "递质的一天", tag: "番外日常", hook: "从早上醒来到夜里入睡，大脑里的递质们都在忙些什么？",
      desc: "轻松的番外篇：跟着递质们过完一整天，顺便弄懂昼夜节律、专注和困意从哪来。", eps: ["早高峰：皮质醇叫醒全员", "午后犯困的真相", "夜班交接：谁在守护睡眠"] },
    { key: "ACh", name: "看完考考你", tag: "小测验", hook: "看完一集，还记得回收门和受体谁是谁吗？",
      desc: "每集结尾三道小题，答对就能盖一枚小印章，集满一章就能点亮一枚徽章。", eps: ["突触篇小测验", "抗抑郁药篇小测验", "睡眠篇小测验"] },
  ],
  // 角色图鉴：key 对应 Anima.CAST 里的角色
  cast: [
    { key: "DA", role: "奖赏快递员", home: "中脑（腹侧被盖区、黑质）", desc: "元气满满的双马尾，负责“想要”和“动力”，也管动作的启动和注意力。在某些通路里太多，可能出现幻觉妄想；太少，会没劲、动作变慢。" },
    { key: "5HT", role: "心情调律师", home: "脑干的中缝核", desc: "温柔稳重，帮忙调节情绪、焦虑、睡眠和食欲。很多抗抑郁药做的事，就是让她在突触里多留一会儿。" },
    { key: "NE", role: "警戒哨兵", home: "脑干的蓝斑", desc: "吹着哨子的红发哨兵，让人清醒、专注、警觉。太少会注意力涣散，太多会紧张心慌。" },
    { key: "GABA", role: "安静的图书管理员", home: "遍布全脑的中间神经元", desc: "戴眼镜、总是说“嘘——”。她是大脑里最主要的刹车，让过度兴奋的神经元安静下来。" },
    { key: "Glu", role: "油门少年", home: "遍布全脑的锥体神经元", desc: "大脑里最主要的兴奋性递质，学习和记忆都离不开他。可他一旦太激动，也会把神经元“累坏”。" },
    { key: "ACh", role: "记忆邮差", home: "基底前脑", desc: "抱着笔记本的邮差，帮忙记东西、集中注意。阿尔茨海默病里，送她的神经元越来越少。" },
    { key: "pump", role: "回收员", home: "突触前膜", desc: "守着回收门，把送完信的递质拉回家、重新装箱。SSRI 类抗抑郁药就是把 5-HT 的回收门先堵上。" },
    { key: "MAO", role: "清扫员", home: "神经末梢里", desc: "拿着扫帚，把多余的多巴胺、5-HT、去甲肾上腺素分解掉。有一类老牌抗抑郁药会让她停工。" },
    { key: "AChE", role: "剪刀手", home: "突触间隙", desc: "在间隙里把乙酰胆碱直接剪断。有的治疗阿尔茨海默病的药，就是让她的剪刀慢一点。" },
    { key: "drug", role: "药物访客", home: "从血液里来", desc: "戴着胶囊帽子的访客：有的堵住回收门，有的冒充钥匙，有的占着锁孔不开门。每集里帽子上写着她的名字。" },
  ],
};
